apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: DOCKER_USERNAME/gitops-full-cycle
  newTag: 6cdd35a56ba1e27f2165499b7f1e3b17cbe7c8a0
